# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Ben's Blog"
description:	       "This blog details my travels and experiences as a Peace Corps volunteer in Tanzania. My views do not neccessarily reflect the opinions of Peace Corps or of the US Government."
author:              "Ben Weber"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
